/**
 * @file actions.cpp
 * @brief This file implements the bridge functions between the C actions defined
 * in EEZ-Flow Studio and our C++ event handler implementations.
 */

#include "actions.h"       // Generated by EEZ-Flow, declares the action_... functions
#include "EventHandler.h"  // Declares our C++ event handlers

/**
 * @brief Bridge for the alarm_edit_screen's LOAD_START, LOADED, and UNLOAD_START events.
 *        EEZ-Flow Action Name: eez_alarm_edit_screen_load_handler
 */
extern "C" void action_eez_alarm_edit_screen_load_handler(lv_event_t *e) {
    alarm_edit_screen_load_handler(e);
}

/**
 * @brief Bridge for the save_alarm_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_save_alarm_button_handler
 */
extern "C" void action_eez_save_alarm_button_handler(lv_event_t *e) {
    save_button_event_handler(e);
}

/**
 * @brief Bridge for the cancel_alarm_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_cancel_alarm_button_handler
 */
extern "C" void action_eez_cancel_alarm_button_handler(lv_event_t *e) {
    cancel_button_event_handler(e);
}

/**
 * @brief Bridge for the add_alarm_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_add_alarm_button_handler
 */
extern "C" void action_eez_add_alarm_button_handler(lv_event_t *e) {
    add_alarm_button_event_handler(e);
}

/**
 * @brief Bridge for the edit_alarm_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_edit_alarm_button_handler
 */
extern "C" void action_eez_edit_alarm_button_handler(lv_event_t *e) {
    edit_button_event_handler(e);
}

/**
 * @brief Bridge for the delete_alarm_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_delete_alarm_button_handler
 */
extern "C" void action_eez_delete_alarm_button_handler(lv_event_t *e) {
    delete_button_event_handler(e);
}

/**
 * @brief Bridge for the show_calendar_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_show_calendar_button_handler
 */
extern "C" void action_eez_show_calendar_button_handler(lv_event_t *e) {
    show_calendar_button_event_handler(e);
}

/**
 * @brief Bridge for the date_selection_ok_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_calendar_ok_button_handler
 */
extern "C" void action_eez_calendar_ok_button_handler(lv_event_t *e) {
    calendar_ok_button_event_handler(e);
}

/**
 * @brief Bridge for the date_selection_cancel_button's CLICKED event.
 *        EEZ-Flow Action Name: eez_calendar_cancel_button_handler
 */
extern "C" void action_eez_calendar_cancel_button_handler(lv_event_t *e) {
    calendar_cancel_button_event_handler(e);
}

/**
 * @brief Bridge for the calendar date selection event handler
 *        EEZ-Flow Action Name: eez_calendar_date_selected
 */
extern "C" void action_eez_calendar_date_selected(lv_event_t *e) {
    calendar_date_selection_event_handler(e);
}
